upstream nodejs_backend {
    server 127.0.0.1:9898;
}

# Node.js Backend API: https://ecom.neuro-mind.net
server {
    listen 443 ssl;
    server_name ecom.neuro-mind.net;

    ssl_certificate /etc/letsencrypt/live/ecom.neuro-mind.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ecom.neuro-mind.net/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 20M;

    # Backend API routing
    location / {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_intercept_errors on;
        proxy_pass http://nodejs_backend;
    }
}

# HTTP -> HTTPS redirect
server {
    listen 80;
    server_name ecom.neuro-mind.net;
    return 301 https://$host$request_uri;
}